apiVersion: v1
kind: Secret
metadata:
  name: newsai-secrets
  namespace: newsai
type: Opaque
data:
  supabase-url: aHR0cHM6Ly9qZWtzaGpmeXh2bm1icXl1YW9zdS5zdXBhYmFzZS5jbw==
  supabase-key: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW1wbGEzTm9hbVo1ZUhadWJXSnhlWFZoYjNOMUlpd2ljbTlzWlNJNkluTmxjblpwWTJWZmNtOXNaU0lzSW1saGRDSTZNVGMzTWpFek56Z3dOaXdpWlhod0lqb3lNRGczTnpFek9EQTJmUS5YOEcwb0l4SVRaeGgwWUxvck1BaW9leW9iZEdzUUFmcGxUZllFT3AwdkdV
  supabase-anon-key: c2JfcHVibGlzaGFibGVfRWJQYUVRTVlFUzJpMXVpX3FweWl6Z19VdzBMc054Vw==
  supabase-jwt-secret: MTBiM2Q5M2ItOWY3YS00NWM1LWFiYTgtNjQ3ZmY1ZDU2N2E4
  mistral-key: N1NOalhqMVN6R3RSdkFUUzdHWjFoNmpqcURKb2pCTVQ=
  firecrawl-key: ZmMtNjEyNjYzYjdmYmU3NDAzOGJmODMxNzM2MWYzZTVkZGM=
